config/routes.rb
GolfLeagueMgr::Application.routes.draw do

  resources :scores
  resources :handicaps
  resources :rounds do
    resources :matches do
      get :show_score_card, to: 'matches#show_score_card'
      get :edit_score_card, to: 'matches#edit_score_card'
      post :update_score_card, to: 'matches#update_score_card'
    end
  end
  resources :leagues
  resources :teams
  resources :golfers
  resources :admins
  resources :rounds
  resources :scores

  get "admins/index"

  devise_for :users

  root :to => 'leagues#index'

end

app/models/golfer.rb
class Golfer < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :user_id

  belongs_to :user
  has_and_belongs_to_many :leagues
  has_and_belongs_to_many :teams
  has_and_belongs_to_many :matches
  has_many :scores
  has_one :handicap

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController
  # GET /golfers
  # GET /golfers.json
  def index
    @golfers = Golfer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @golfers }
    end
  end

  # GET /golfers/1
  # GET /golfers/1.json
  def show
    @golfer = Golfer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @golfer }
    end
  end

  # GET /golfers/new
  # GET /golfers/new.json
  def new
    @golfer = Golfer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @golfer }
    end
  end

  # GET /golfers/1/edit
  def edit
    @golfer = Golfer.find(params[:id])
  end

  # POST /golfers
  # POST /golfers.json
  def create
    @golfer = Golfer.new(params[:golfer])

    respond_to do |format|
      if @golfer.save
        format.html { redirect_to @golfer, notice: 'Golfer was successfully created.' }
        format.json { render json: @golfer, status: :created, location: @golfer }
      else
        format.html { render action: "new" }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /golfers/1
  # PUT /golfers/1.json
  def update
    @golfer = Golfer.find(params[:id])

    respond_to do |format|
      if @golfer.update_attributes(params[:golfer])
        format.html { redirect_to @golfer, notice: 'Golfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @golfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golfers/1
  # DELETE /golfers/1.json
  def destroy
    @golfer = Golfer.find(params[:id])
    @golfer.destroy

    respond_to do |format|
      format.html { redirect_to golfers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/views/golfers/_form.html.erb
<%= form_for(@golfer) do |f| %>
  <% if @golfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@golfer.errors.count, "error") %> prohibited this golfer from being saved:</h2>

      <ul>
      <% @golfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= select(:golfer, 'user_id', User.all.collect {|u| [ u.email, u.id ] }, {:include_blank => true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/golfers/edit.html.erb
<h1>Editing golfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @golfer %> |
<%= link_to 'Back', golfers_path %>

app/views/golfers/index.html.erb
<h1>Listing golfers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @golfers.each do |golfer| %>
  <tr>
    <td><%= golfer.first_name %></td>
    <td><%= golfer.last_name %></td>
    <td><%= golfer.user.email %></td>
    <td><%= link_to 'Show', golfer %></td>
    <td><%= link_to 'Edit', edit_golfer_path(golfer) %></td>
    <td><%= link_to 'Destroy', golfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Golfer', new_golfer_path %>

app/views/golfers/new.html.erb
<h1>New golfer</h1>

<%= render 'form' %>

<%= link_to 'Back', golfers_path %>

app/views/golfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @golfer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @golfer.last_name %>
</p>

<p>
  <b>User:</b>
  <%= @golfer.user.email %>
</p>


<%= link_to 'Edit', edit_golfer_path(@golfer) %> |
<%= link_to 'Back', golfers_path %>