config/routes.rb
GolfLeagueMgr::Application.routes.draw do

  resources :scores
  resources :handicaps
  resources :rounds do
    resources :matches do
      get :show_score_card, to: 'matches#show_score_card'
      get :edit_score_card, to: 'matches#edit_score_card'
      post :update_score_card, to: 'matches#update_score_card'
    end
  end
  resources :leagues
  resources :teams
  resources :golfers
  resources :admins
  resources :rounds
  resources :scores

  get "admins/index"

  devise_for :users

  root :to => 'leagues#index'

end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :course_id, :date, :number

  has_and_belongs_to_many :teams
  has_many :matches
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def index
    @rounds = Round.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @round = Round.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(params[:round])

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'round was successfully created.' }
        format.json { render json: @round, status: :created, location: @round }
      else
        format.html { render action: "new" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id])

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to @round, notice: 'round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /round/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
    <% if @round.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% @round.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :number %>
      <br/>
      <%= f.text_field :number %>
    </div>
    <div class="field">
      <%= f.label :date %>
      <br/>
      <%= f.date_select :date %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:team, 'first_opponent', Team.all.collect { |u| [u.name, u.id] }, {:include_blank => true}) %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:team, 'second_opponent', Team.all.collect { |u| [u.name, u.id] }, {:include_blank => true}) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Listing Rounds</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @rounds.each do |round| %>
      <tr>
        <td><%= round.number %></td>
        <td><%= round.date %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Matches', round_matches_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @round.number %>
</p>

<p>
  <b>Date:</b>
  <%= @round.date %>
</p>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>