config/routes.rb
GolfLeagueMgr::Application.routes.draw do

  resources :scores
  resources :handicaps
  resources :rounds do
    resources :matches do
      get :show_score_card, to: 'matches#show_score_card'
      get :edit_score_card, to: 'matches#edit_score_card'
      post :update_score_card, to: 'matches#update_score_card'
    end
  end
  resources :leagues
  resources :teams
  resources :golfers
  resources :admins
  resources :rounds
  resources :scores

  get "admins/index"

  devise_for :users

  root :to => 'leagues#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :date, :league_id, :name, :round_id, :is_front_side, :round

  belongs_to :league
  has_and_belongs_to_many :golfers
  belongs_to :round


  def create_score_card
    if is_front_side?
      create_front_side_scores()
    else
      create_back_side_scores()
    end
    calculate_handicap_strokes
  end

  def create_front_side_scores
    golfers.each do |golfer|
      i = 1
      9.times do
        Score.create(:hole_id => i, :match_id => id, :golfer_id => golfer.id)
        i += 1
      end
    end
  end

  def create_back_side_scores
    golfers.each do |golfer|
      i = 10
      9.times do
        Score.create(:hole_id => i, :match_id => id, :golfer_id => golfer.id)
        i += 1
      end
    end
  end

  def calculate_handicap_strokes
    first_golfer_handicap = golfers[0].handicap.score
    second_golfer_handicap = golfers[1].handicap.score

    if first_golfer_handicap > second_golfer_handicap
      golfer_handicap_strokes = first_golfer_handicap - second_golfer_handicap
      golfer_receiving_strokes = Golfer.find(golfers[0].id)
    else
      golfer_handicap_strokes = second_golfer_handicap - first_golfer_handicap
      golfer_receiving_strokes = Golfer.find(golfers[1].id)
    end

    if is_front_side
      holes = Hole.front_side_holes.order('handicap asc').limit(golfer_handicap_strokes)
    else
      holes = Hole.back_side_holes.order('handicap asc').limit(golfer_handicap_strokes)
    end

    holes.each do |hole|
      score = Score.where('hole_id = ? and match_id = ? and golfer_id = ?', hole.id, id, golfer_receiving_strokes.id).first
      score.handicap_strokes = 1
      score.save
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.includes(:golfers).where('round_id = ?', params[:round_id])
    @total_strokes = 0

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  def show_score_card
    @match = Match.find(params[:match_id])
    @scores = Score.where('match_id = ?', @match.id)
    @total_strokes = 0
    @total_par = 0
    @total_handicap_strokes = 0

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @round = Round.find(params[:round_id])
    @match = Match.new(:round => @round)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @round = Round.find(1)
    @match = Match.find(params[:id])
  end

  def edit_score_card
    @round = Round.find(1)
    @match = Match.find(params[:match_id])
    @scores = Score.where('match_id = ?', @match.id)
    @total_strokes = 0
    @total_par = 0
    @total_handicap_strokes = 0

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scores }
    end
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])
    @match.round_id = params[:round_id]
    first_opponent = params[:golfer][:first_opponent]
    second_opponent = params[:golfer][:second_opponent]
    @match.golfers << Golfer.find(first_opponent)
    @match.golfers << Golfer.find(second_opponent)

    respond_to do |format|
      if @match.save
        @match.create_score_card
        format.html { redirect_to round_matches_path, notice: 'Match and Scorecard were successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])
    @match.calculate_handicap_strokes

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to round_match_url, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_score_card
    @scores = Score.update(params[:scores].keys, params[:scores].values).reject { |s| s.errors.empty? }
    if @scores.empty?
      flash[:notice] = 'Scorecard was successfully updated'
      redirect_to round_match_show_score_card_url
    else
      render :action => 'edit_score_card'
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to round_matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for([@round, @match]) do |f| %>
    <% if @match.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% @match.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :league_id %>
      <br/>
      <%= select(:match, 'league_id', League.all.collect { |u| [u.name, u.id] }, {:selected => '1'}) %>
    </div>
    <div class="field">
      <%= f.label 'Date - Time' %>
      <br/>
      <%= f.datetime_select :date, ampm: true, :default => {:month => @match.date.month, :day => @match.date.day, :year => @match.date.year, :hour => @match.date.hour, :minute => @match.date.min } %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name, :value => @match.name %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:golfer, 'first_opponent', Golfer.all.collect { |u| [u.full_name, u.id] }, {:include_blank => true, :selected => @match.golfers[0].id}) %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:golfer, 'second_opponent', Golfer.all.collect { |u| [u.full_name, u.id] }, {:include_blank => true, :selected => @match.golfers[1].id}) %>
    </div>
    <div class="field">
      <%= f.radio_button(:is_front_side, 1, :checked => @match.is_front_side) %>
      <%= f.label 'Front Side' %>
      <br/>
      <%= f.radio_button(:is_front_side, 0, :checked => !@match.is_front_side)  %>
      <%= f.label 'Back Side' %>
    </div>
    <div class="actions">
      <%= f.submit 'Update Match' %>
    </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', round_match_path(@match.round.id, @match) %> |
<%= link_to 'Back', round_matches_path(@match.round.id) %>

app/views/matches/edit_score_card.html.erb
<h1>Edit Scores for the Match</h1>

<%= form_tag round_match_update_score_card_path(@match.round.id, @match) do %>
    <% @scores.each do |score| %>
        <%= fields_for "scores[]", score do |f| %>
        <% if score.hole.number == 1 || score.hole.number == 10 %>
            <div class="float-left">
              <div style="padding: 5px">
                <span style="color: #000000; font-weight: bold">Golfer:</span> <%= score.golfer.full_name %>
              </div>
              <div style="padding: 5px">
                <span style="color: #0000ff; font-weight: bold">Handicap:</span> <%= score.golfer.handicap.score %>
              </div>
            </div>
        <% end %>
        <div class="float-left">
          <% if score.hole.number == 1 || score.hole.number == 10 %>
              <div class="float-left">
                <div class="score-card-hole">Hole</div>
                <div class="score-card-par">Par</div>
                <div class="score-card-handicap">Handicap</div>
                <div class="score-card-score">Handicap Strokes</div>
                <div class="score-card-edit-score">Score</div>
              </div>
          <% end %>
          <div class="float-left">
            <div class="score-card-hole"><%= score.hole.number %></div>
            <div class="score-card-par"><%= score.hole.par %></div>
            <div class="score-card-handicap"><%= score.hole.handicap %></div>
            <div class="score-card-score"><%= score.handicap_strokes %></div>
            <div class="score-card-score">
              <%= f.number_field :strokes, {:min => 0, :size => 2, :style => "width:30px"} %>
              <% score.strokes.nil? ? @total_strokes = @total_strokes + 0 : @total_strokes = @total_strokes + score.strokes %>
              <% @total_par = @total_par + score.hole.par %>
              <% @total_handicap_strokes = @total_handicap_strokes + score.handicap_strokes %>
            </div>
          </div>

        </div>
        <% if score.hole.number == 9 || score.hole.number == 18 %>
            <div class="float-left">
              <div class="score-card-hole">Total</div>
              <div class="score-card-par"><%= @total_par %></div>
              <div class="score-card-handicap">&nbsp;</div>
              <div class="score-card-score"><b><%= @total_handicap_strokes %></b></div>
              <div class="score-card-edit-score"><b><%= @total_strokes %></b></div>
              <% @total_strokes = 0 %>
              <% @total_par = 0 %>
            </div>
            <div style="clear:both; padding-bottom: 20px"></div>
        <% end %>
        <% end %>
    <% end %>


    <div class="actions">
      <%= submit_tag "Submit" %>
    </div>
<% end %>

<%= link_to 'Back', round_match_show_score_card_path(@match.round.id, @match) %>

app/views/matches/index.html.erb
<h1>Listing Matches</h1>

<table>
  <tr>
    <th>League</th>
    <th>Date - Time</th>
    <th>Name</th>
    <th>Opponents</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.league.name %></td>
    <td><%= match.date.localtime.strftime('%B %-d %Y - %l:%M %p') %></td>
    <td><%= match.name %></td>
    <td>
        <%= match.golfers[0].full_name %> vs. <%= match.golfers[1].full_name %>
    </td>
    <td><%= link_to 'Show', round_match_path(match.round.id, match) %></td>
    <td><%= link_to 'Edit', edit_round_match_path(match.round.id, match) %></td>
    <td><%= link_to 'Score Card', round_match_show_score_card_path(match.round.id, match) %></td>
    <td><%= link_to 'Destroy', round_match_path(match.round.id, match), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_round_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= form_for([@round, @match]) do |f| %>
    <% if @match.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

          <ul>
            <% @match.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :league_id %>
      <br/>
      <%= select(:match, 'league_id', League.all.collect { |u| [u.name, u.id] }, {:selected => '1'}) %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :date %>
      <br/>
      <%= f.datetime_select :date, ampm: true %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:golfer, 'first_opponent', Golfer.all.collect { |u| [u.full_name, u.id] }, {:include_blank => true}) %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %>
      <br/>
      <%= select(:golfer, 'second_opponent', Golfer.all.collect { |u| [u.full_name, u.id] }, {:include_blank => true}) %>
    </div>
    <div class="field">
      <%= radio_button(:match, :is_front_side, 1, :checked => true) %>
      <%= f.label 'Front Side' %>
      <br/>
      <%= radio_button(:match, :is_front_side, 0) %>
      <%= f.label 'Back Side' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', round_matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>League:</b>
  <%= @match.league.name %>
</p>
<p>
  <b>Date - Time:</b>
  <%= @match.date.localtime.strftime('%B %-d %Y - %l:%M %p') %>
</p>
<p>
  <b>Name:</b>
  <%= @match.name %>
</p>
<p>
  <b>Opponents:</b>
  <%= @match.golfers[0].full_name %> vs. <%= @match.golfers[1].full_name %>
</p>
<p>
  <b>Front Side:</b>
  <%= @match.is_front_side ? 'YES' : 'NO' %>
</p>
<p>
  <b>Back Side:</b>
  <%= @match.is_front_side ? 'NO' : 'YES' %>
</p>

<%= link_to 'Edit', edit_round_match_path(@match.round.id) %> |
<%= link_to 'Back', round_matches_path %>

app/views/matches/show_score_card.html.erb
<h1>Listing Scores for the Match</h1>

<% @scores.each do |score| %>
    <% if score.hole.number == 1 || score.hole.number == 10 %>
        <div class="float-left">
            <div style="padding: 5px">
              <span style="color: #000000; font-weight: bold">Golfer:</span> <%= score.golfer.full_name %>
            </div>
            <div style="padding: 5px">
              <span style="color: #0000ff; font-weight: bold">Handicap:</span> <%= score.golfer.handicap.score %>
            </div>
        </div>
    <% end %>
    <div class="float-left">
      <% if score.hole.number == 1 || score.hole.number == 10 %>
          <div class="float-left">
            <div class="score-card-hole">Hole</div>
            <div class="score-card-par">Par</div>
            <div class="score-card-handicap">Handicap</div>
            <div class="score-card-score">Handicap Strokes</div>
            <div class="score-card-score">Score</div>
          </div>
      <% end %>
      <div class="float-left">
        <div class="score-card-hole"><%= score.hole.number %></div>
        <div class="score-card-par"><%= score.hole.par %></div>
        <div class="score-card-handicap"><%= score.hole.handicap %></div>
        <div class="score-card-score"><%= score.handicap_strokes %></div>
        <div class="score-card-score">
          <%= score.strokes.nil? ? '?' : score.strokes %>
          <% score.strokes.nil? ? @total_strokes = @total_strokes + 0 : @total_strokes = @total_strokes + score.strokes %>
          <% @total_par = @total_par + score.hole.par %>
          <% @total_handicap_strokes = @total_handicap_strokes + score.handicap_strokes %>
        </div>
      </div>

    </div>
    <% if score.hole.number == 9 || score.hole.number == 18 %>
        <div class="float-left">
          <div class="score-card-hole">Total</div>
          <div class="score-card-par"><%= @total_par %></div>
          <div class="score-card-handicap">&nbsp;</div>
          <div class="score-card-score"><%= @total_handicap_strokes %></div>
          <div class="score-card-score"><b><%= @total_strokes %></b></div>
        </div>
        <div style="clear:both; padding-bottom: 20px"></div>
        <% @total_strokes = 0 %>
        <% @total_par = 0 %>
    <% end %>
<% end %>

<br/>

<%= link_to 'Edit', round_match_edit_score_card_path(@match.round.id, @match.id) %> |
<%= link_to 'Matches', round_matches_path %>