config/routes.rb
GolfLeagueMgr::Application.routes.draw do

  resources :scores
  resources :handicaps
  resources :rounds do
    resources :matches do
      get :show_score_card, to: 'matches#show_score_card'
      get :edit_score_card, to: 'matches#edit_score_card'
      post :update_score_card, to: 'matches#update_score_card'
    end
  end
  resources :leagues
  resources :teams
  resources :golfers
  resources :admins
  resources :rounds
  resources :scores

  get "admins/index"

  devise_for :users

  root :to => 'leagues#index'

end

app/models/handicap.rb
class Handicap < ActiveRecord::Base
  attr_accessible :date, :golfer_id, :league_id, :score

  belongs_to :golfer

end

app/controllers/handicaps_controller.rb
class HandicapsController < ApplicationController
  # GET /handicaps
  # GET /handicaps.json
  def index
    @handicaps = Handicap.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handicaps }
    end
  end

  # GET /handicaps/1
  # GET /handicaps/1.json
  def show
    @handicap = Handicap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handicap }
    end
  end

  # GET /handicaps/new
  # GET /handicaps/new.json
  def new
    @handicap = Handicap.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handicap }
    end
  end

  # GET /handicaps/1/edit
  def edit
    @handicap = Handicap.find(params[:id])
  end

  # POST /handicaps
  # POST /handicaps.json
  def create
    @handicap = Handicap.new(params[:handicap])

    respond_to do |format|
      if @handicap.save
        format.html { redirect_to @handicap, notice: 'Handicap was successfully created.' }
        format.json { render json: @handicap, status: :created, location: @handicap }
      else
        format.html { render action: "new" }
        format.json { render json: @handicap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /handicaps/1
  # PUT /handicaps/1.json
  def update
    @handicap = Handicap.find(params[:id])

    respond_to do |format|
      if @handicap.update_attributes(params[:handicap])
        format.html { redirect_to @handicap, notice: 'Handicap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @handicap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handicaps/1
  # DELETE /handicaps/1.json
  def destroy
    @handicap = Handicap.find(params[:id])
    @handicap.destroy

    respond_to do |format|
      format.html { redirect_to handicaps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/handicaps_helper.rb
module HandicapsHelper
end

app/views/handicaps/_form.html.erb
<%= form_for(@handicap) do |f| %>
  <% if @handicap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handicap.errors.count, "error") %> prohibited this handicap from being saved:</h2>

      <ul>
      <% @handicap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :golfer_id %><br />
    <%= f.number_field :golfer_id %>
  </div>
  <div class="field">
    <%= f.label :league_id %><br />
    <%= f.number_field :league_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handicaps/edit.html.erb
<h1>Editing handicap</h1>

<%= render 'form' %>

<%= link_to 'Show', @handicap %> |
<%= link_to 'Back', handicaps_path %>

app/views/handicaps/index.html.erb
<h1>Listing handicaps</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Date</th>
    <th>Golfer</th>
    <th>League</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @handicaps.each do |handicap| %>
  <tr>
    <td><%= handicap.score %></td>
    <td><%= handicap.date %></td>
    <td><%= handicap.golfer_id %></td>
    <td><%= handicap.league_id %></td>
    <td><%= link_to 'Show', handicap %></td>
    <td><%= link_to 'Edit', edit_handicap_path(handicap) %></td>
    <td><%= link_to 'Destroy', handicap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Handicap', new_handicap_path %>

app/views/handicaps/new.html.erb
<h1>New handicap</h1>

<%= render 'form' %>

<%= link_to 'Back', handicaps_path %>

app/views/handicaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @handicap.score %>
</p>

<p>
  <b>Date:</b>
  <%= @handicap.date %>
</p>

<p>
  <b>Golfer:</b>
  <%= @handicap.golfer_id %>
</p>

<p>
  <b>League:</b>
  <%= @handicap.league_id %>
</p>


<%= link_to 'Edit', edit_handicap_path(@handicap) %> |
<%= link_to 'Back', handicaps_path %>